// examples/react/src/components/Checkbox.tsx
import * as checkbox from '@destyler/checkbox'
import { mergeProps, normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'

export default function Checkbox() {
  const [state, send] = useMachine(
    checkbox.machine({
      id: useId(),
    }),
  )

  const api = checkbox.connect(state, send, normalizeProps)

  const inputProps = mergeProps(api.inputProps, {
    onChange() {
      if (api.isIndeterminate && !api.isReadOnly) {
        api.setIndeterminate(false)
        api.setChecked(true)
      }
    },
  })

  return (
    <>
      <main className="checkbox">
        <form>
          <fieldset>
            <label {...api.rootProps}>
              <span {...api.labelProps}>
                Input
                {' '}
                {api.isChecked ? 'Checked' : 'Unchecked'}
              </span>
              <input {...inputProps} />
              <div style={{ border: '1px solid', width: '10px', height: '10px' }} {...api.controlProps} />
            </label>

            <button type="button" disabled={api.isChecked} onClick={() => api.setChecked(true)}>
              Check
            </button>
            <button type="button" disabled={!api.isChecked} onClick={() => api.setChecked(false)}>
              UnCheck
            </button>
            <button type="reset">Reset Form</button>
          </fieldset>
        </form>
      </main>
    </>
  )
}

// examples/vue/src/components/Checkbox.vue
<script setup lang="ts">
import { computed } from 'vue'
import * as checkbox from '@destyler/checkbox'
import { useMachine,normalizeProps,mergeProps } from '@destyler/vue'

const [state, send] = useMachine(checkbox.machine({ id: "accordion" }))

const api = computed(() => checkbox.connect(state.value, send, normalizeProps))

const inputProps = mergeProps(api.value.inputProps, {
        onChange() {
          if (api.value.isIndeterminate && !api.value.isReadOnly) {
            api.value.setIndeterminate(false)
            api.value.setChecked(true)
          }
        },
      })

</script>

<template>
  <form>
              <fieldset>
                <label v-bind="{...api.rootProps}">
                  <span v-bind="{...api.labelProps}">Input {{ api.isChecked ? "Checked" : "Unchecked" }}</span>
                  <input v-bind="{...inputProps}" />
                  <div v-bind="{...api.controlProps}" style="border: 1px solid; width: 10px;height: 10px;" />
                </label>

                <button type="button" :disabled="api.isChecked" @click="api.setChecked(true)">
                  Check
                </button>
                <button type="button" :disabled="!api.isChecked" @click="api.setChecked(false)">
                  UnCheck
                </button>
                <button type="reset">Reset Form</button>
              </fieldset>
            </form>
</template>
