// examples/vue/src/components/Accordion.vue
<script setup lang="ts">
import { computed } from 'vue'
import * as accordion from '@destyler/accordion'
import { useMachine,normalizeProps } from '@destyler/vue'

const [state, send] = useMachine(accordion.machine({ id: "accordion" }))

const apiRef = computed(() => accordion.connect(state.value, send, normalizeProps))

const accordionData = [
  { id: "home", label: "Home" },
  { id: "about", label: "About" },
  { id: "contact", label: "Contact" },
]
</script>

<template>
  <div v-bind="{...apiRef.rootProps}">
    <div v-for="accordion in accordionData" :key="accordion.id" v-bind="{...apiRef.getItemProps({value: accordion.id})}">
      <button v-bind="{...apiRef.getTriggerProps({ value: accordion.id })}">
        {{ accordion.label }}
      </button>
      <div v-bind="{...apiRef.getContentProps({ value: accordion.id })}">
        this is {{ accordion.id }} {{ accordion.label }}
      </div>
    </div>
  </div>
</template>

// examples/react/src/components/Accordion.tsx
import * as accordion from '@destyler/accordion'
import { normalizeProps, useMachine } from '@destyler/react'
import { useId } from 'react'

function Accordion() {
  const [state, send] = useMachine(
    accordion.machine({
      id: useId(),
    }),
  )

  const api = accordion.connect(state, send, normalizeProps)

  const accordionData = [
    { id: 'home', label: 'Home' },
    { id: 'about', label: 'About' },
    { id: 'contact', label: 'Contact' },
  ]
  return (
    <>
      <div {...api.rootProps}>
        {accordionData.map(item => (
          <div key={item.id} {...api.getItemProps({ value: item.id })}>
            <button {...api.getTriggerProps({ value: item.id })}>
              {item.label}
            </button>
            <div {...api.getContentProps({ value: item.id })}>
              this is
              {' '}
              { item.id }
              {' '}
              { item.label }
            </div>
          </div>
        ))}
      </div>
    </>
  )
}

export default Accordion
